version: '2'

services:
  nginx:
    build: nginx
    restart: always
    ports:
      - 80:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pswrd
      POSTGRES_USER: user
      POSTGRES_MULTIPLE_DATABASES: rucas, metabase
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
      - ./postgres-data/entrypoint:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      - MB_SITE_URL=http://localhost/metabase/
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER= user
      - MB_DB_PASS= pswrd
      - MB_DB_HOST=db     
    ports:
      - 3000:3000
    depends_on:
      - db

  minio:
    image: minio/minio
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: user
      MINIO_SECRET_KEY: pswrd
    command: server /data
